routes/auth_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from flask_login import login_user, logout_user, login_required
from models import Usuarios
from models_rrhh import UsuariosRRHH
from models import obtener_roles
from controllers.user_controller import insertar_usuario

auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        tipo_login = request.form.get('tipo_login')
        
        user = None
        
        if tipo_login == 'sgi':
            user = Usuarios.obtener_por_username(username)
        elif tipo_login == 'rrhh':
            user = UsuariosRRHH.obtener_por_identificacion_correo(username)
        elif tipo_login == 'aula':
            flash('Modulo de aula vortual en contruccion', 'error')
            return redirect(url_for('auth.login'))
        
        if user and user.verifica_contrasena(password):
            session.pop('selected_rol', None)
            login_user(user)
            if tipo_login == 'rrhh':
                return redirect(url_for('rrhh.dashboard'))
            elif tipo_login == 'aula':
                return redirect(url_for('aula.aula'))
            else:
                return redirect(url_for('home.home'))
        
        flash('Usuario o contraseña incorrectos', 'error')
        return redirect(url_for('auth.login'))
    return render_template('log_reg/login.html')
            
        
@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        name = request.form.get('name')
        username = request.form.get('username')
        password = request.form.get('password')
        rol = request.form.get('rol')

        insertar_usuario(name, username, password, rol)
        flash("Usuario creado correctamente")
        return redirect(url_for('auth.login'))
    roles =  obtener_roles()
    return render_template('log_reg/register.html', roles=roles)

@auth_bp.route('/logout')
@login_required
def logout():
    # Limpiar la sesión del rol seleccionado
    if 'selected_rol' in session:
        session.pop('selected_rol', None)
    
    logout_user()
    return redirect(url_for('auth.login'))

templates/log_reg/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
</head>

<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <svg width="100%" height="120" viewBox="0 0 1200 120" preserveAspectRatio="xMidYMin meet"
        style="position: absolute; top: 20px; left: 0; z-index: 10;">
        <defs>
            <!-- Curva más amplia y suave para texto largo -->
            <path id="arc-path" d="M50,60 Q600,0 1150,60" fill="none" stroke="none" />
        </defs>
        <text font-family="Poppins, sans-serif" font-size="22" fill="#23a2f6" text-anchor="middle">
            <textPath href="#arc-path" startOffset="50%" textLength="1100" lengthAdjust="spacingAndGlyphs">
                Sistema de Gestion Integrado - DIGICOM SYSTEM CORPORATION S.A
            </textPath>
        </text>
    </svg>
    {% with messages = get_flashed_messages(with_categories=true ) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="login-error-msg alert-{{ category }}">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}


    <div class="login-container">
        <div class="login-tabs">
            <button type="button" class="tab-btn active" onclick="showLogin('sgi', this)">SGI</button>
            <button type="button" class="tab-btn" onclick="showLogin('rrhh', this)">RRHH</button>
            <button type="button" class="tab-btn" onclick="showLogin('aula', this)">Aula Virtual</button>
        </div>
        <div class="login-slider">
            <!-- LOGIN SGI -->
            <form id="login-sgi" class="login-form active" method="POST" action="{{ url_for('auth.login') }}">


                <input type="hidden" name="tipo_login" value="sgi">
                <label for="username">Usuario</label>
                <input type="text" name="username" placeholder="Usuario" id="username">

                <label for="password">Contraseña</label>
                <input type="password" name="password" placeholder="Contraseña" id="password">

                <button type="submit">Ingresa a SGI</button>
                <!-- <div class="social">

            <div class="go"><a href="{{ url_for('aula.aula') }}">Aula Virtual</a></div>
        </div> -->
            </form>

            <!-- LOGIN RRHH -->
            <form id="login-rrhh" class="login-form" method="POST" action="{{ url_for('auth.login') }}">

                <input type="hidden" name="tipo_login" value="rrhh">
                <label for="username">Usuario</label>
                <input type="text" name="username" placeholder="Usuario" id="username">

                <label for="password">Contraseña</label>
                <input type="password" name="password" placeholder="Contraseña" id="password">

                <button type="submit">Ingresa a RRHH</button>
            </form>

            <!-- LOGIN AULA -->
            <form id="login-aula" class="login-form" method="POST" action="{{ url_for('auth.login') }}">

                <input type="hidden" name="tipo_login" value="aula">
                <label for="username">Numero de identificacion</label>
                <input type="text" name="username" id="username">

                <button type="submit">Ingresa al Aula Virtual</button>
                <!-- <div class="social">

            <div class="go"><a href="{{ url_for('aula.aula') }}">Aula Virtual</a></div>
        </div> -->
            </form>
        </div>
    </div>

    <script>
        function showLogin(tipo, btn) {
            const slide = document.querySelector('.login-slider');
            const tabs = document.querySelectorAll('.tab-btn');

            let index = 0;
            if (tipo === 'rrhh') index = 1;
            if (tipo === 'aula') index = 2;

            slide.style.transform = `translateX(-${index * 33.333}%)`;

            tabs.forEach(t => t.classList.remove('active'));
            btn.classList.add('active');
        }
    </script>
    <script>
        document.addEventListener('DOMContentLoaded', () =>{
            const errorMsg = document.querySelector('.login-error-msg');

            if (errorMsg){
                const activeForm = document.querySelector('.login-form');

                if (activeForm){
                    activeForm.classList.remove('login-error');
                    void activeForm.offsetWidth;
                    activeForm.classList.add('login-error');
                }
            }
        })
    </script>
</body>
<!-- <div class="go"><a href="{{ url_for('auth.register') }}">¿No tienes cuenta? Regístrate</a></div> -->

</html>

templates/log_reg/register.html
<!DOCTYPE html>
<html lang="en">
<head> 
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/register.css') }}">
</head>
<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form method="POST" action="{{ url_for('auth.register') }}">
        <h3>Login Here</h3>

        <label for="name">Name</label>
        <input type="text" name="name" placeholder="Name" id="name">

        <label for="username">Username</label>
        <input type="text" name="username" placeholder="Username" id="username">

        <label for="password">Password</label>
        <input type="password" name="password" placeholder="Password" id="password">

        <label for="rol">Selecciona el Rol</label>
        <select name="rol" id="rol" required>
            {% for rol in roles %}
                <option value="{{ rol[0] }}">{{ rol[1] }}</option>
            {% endfor %}
        </select>

        <button type="submit">Log Up</button>
    </form>
    
</body>
</html>